spring:
  application:
    name: idms-web

  config:
    import: optional:classpath:application-secrets.yml

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  data:
    redis:
      url: ${REDIS_URL:}

  main:
    banner-mode: off

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_OAUTH2_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH2_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

  session:
    redis:
      repository-type: indexed

  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
