-- change user_email_address.id to bigint generated by default as identity
alter table "user_email_address"
  alter column "id" drop default,
  alter column "id" type bigint using "id"::bigint,
  alter column "id" add generated by default as identity;

-- change user_phone_number.id to bigint generated by default as identity
alter table "user_phone_number"
  alter column "id" drop default,
  alter column "id" type bigint using "id"::bigint,
  alter column "id" add generated by default as identity;

-- drop id column from user_profile and use sub as primary key
alter table "user_profile"
  drop constraint "user_profile_pkey",
  drop constraint "user_profile_sub_key",
  drop column "id",
  add constraint "user_profile_pkey" primary key ("sub");
