create table "user_account" (
  "id" bigint generated by default as identity,
  "user_id" char(36) not null,
  "provider_type" varchar(63) not null,
  "provider" varchar(63) not null,
  "provider_account_id" varchar(255) not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "user_account_pkey" primary key ("id"),
  constraint "user_account_user_id_fkey" foreign key ("user_id")
    references "users" ("id") on delete cascade
);

create index "user_account_user_id_idx" on "user_account" ("user_id");
create index "user_account_provider_provider_account_id_idx"
  on "user_account" ("provider", "provider_account_id");
