create table "tenant" (
  "id" bigint generated by default as identity,
  "name" varchar(255) not null,
  "slug" varchar(63) not null,
  "type" varchar(63) not null,
  "status" varchar(31) not null,
  "owner_id" char(36) not null,
  "created_at" timestamp not null default current_timestamp,
  "updated_at" timestamp not null default current_timestamp,
  constraint "tenant_pkey" primary key ("id"),
  constraint "tenant_slug_key" unique ("slug"),
  constraint "tenant_owner_id_fkey" foreign key ("owner_id")
    references "users" ("id") on delete cascade
);

create index "tenant_owner_id_idx" on "tenant" ("owner_id");
